Clinic/Models/AccountViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Clinic.Models
{
    public class LoginViewModel
    {
        [Required]
        [Display(Name = "Username")]
        [EmailAddress]
        public string Username { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }
        
    }
}

Clinic/Models/ClinicModel.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClinicEntities : DbContext
    {
        public ClinicEntities()
            : base("name=ClinicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> User { get; set; }
    }
}

Clinic/Models/ClinicModel.Designer.cs
// T4 code generation is enabled for model 'C:\Users\behzad\Documents\Visual Studio 2015\Projects\Clinic\Clinic\Models\ClinicModel.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

Clinic/Models/ClinicModel.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

Clinic/Models/Paitient.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Clinic.Models
{
    public class Paitient
    {
        public string Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CreationDate { get; set; }
    }
}

Clinic/Models/User.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Role { get; set; }
    }
}

Clinic/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Clinic.Models;
using System.Web.Security;

namespace Clinic.Controllers
{
    public class AccountController : Controller
    {
        /// <summary>
        /// Check Username and Password 
        /// </summary>
        private bool IsValid(string username, string password)
        {

            bool IsValid = false;

            using (var db = new Models.ClinicEntities())
            {
                var user = db.User.FirstOrDefault(u => u.Username == username);
                if (user != null)
                {
                    if (user.Password == password)
                    {
                        IsValid = true;
                    }
                }
                return IsValid;
            }
        }
        
        /// <summary>
        /// Redirect User to Dashboard if its Authenticated
        /// </summary>
        [AllowAnonymous]
        public ActionResult Login(User user)
        {
            if (user != null)
            {
                var db = new Models.ClinicEntities();
                var us = db.User.FirstOrDefault(u => u.Username == user.Username && u.Password == user.Password);
                if (IsValid(user.Username, user.Password))
                {
                    FormsAuthentication.SetAuthCookie(user.Username, false);
                    Session["uid"] = us.Id;
                    ViewBag.Name = user.Name;
                    return RedirectToAction("Dashboard", "Home",user);
                }
                else
                {
                    ModelState.AddModelError("", "Login Unssucces");
                }
                return View(user);
            }
            return View("~/Views/Account/Login.cshtml");
        }

        /// <summary>
        /// Logout
        /// </summary>
        public ActionResult LogOut()
        {
            FormsAuthentication.SignOut();
            Session["uid"] = null;
            ViewBag.Name = null;
            return RedirectToAction("Login", "Account");
        }

    }
}

Clinic/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Clinic.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Dashboard()
        {
            if (Session["uid"] == null)
            {
                return View("~/Views/Account/Login.cshtml");
            }
            return View("Dashboard");
        }
    }
}

Clinic/Controllers/PaitientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Clinic.Controllers
{
    public class PaitientController : Controller
    {
        public ActionResult CreateNewPaitient()
        {
            return View("CreateNewPaitient");
        }
        public ActionResult ListOfPaitient()
        {
            return View("ListOfPaitients");
        }
    }
}

Clinic/Views/Home/Dashboard.cshtml
@{
    Layout = "~/Views/Shared/_DashLayout.cshtml";
}


@model Clinic.Models.User

@{
    var id = Convert.ToInt32(Session["uid"].ToString());
    var u = new Clinic.Models.ClinicEntities().User.FirstOrDefault(us => us.Id == id); ;
}

<div class="row">
    <div class="container-fluid">
        <h1 class="page-header">داشبورد</h1>
    </div>
</div>
<div class="row">
    <div class="col-lg-4">
        <div class="glob-bar">
            <div class="glob-bar-icon pull-right">
                <i class="fa fa-user-md fa-5x"></i>
            </div>
            <div class="glob-bar-body pull-left">
                <p style="padding-bottom: 10px; border-bottom: thin solid #e5e5e5">جناب آقای <b>@u.Name </b> <small>به سامانه خوش آمدید.</small> </p>
                1
            </div>
        </div>
    </div>

    <div class="col-lg-4">
        <div class="glob-bar">
            <div class="glob-bar-icon pull-right">
                <i class="fa fa-user-md fa-5x"></i>
            </div>
            <div class="glob-bar-body pull-left">
                <p style="padding-bottom: 10px; border-bottom: thin solid #e5e5e5">جناب آقای <b>@Session["uid"].ToString()</b> <small>به سامانه خوش آمدید.</small> </p>
                2
            </div>
        </div>
    </div>

    <div class="col-lg-4">
        <div class="glob-bar">
            <div class="glob-bar-icon pull-right">
                <i class="fa fa-user-md fa-5x"></i>
            </div>
            <div class="glob-bar-body pull-left">
                <p style="padding-bottom: 10px; border-bottom: thin solid #e5e5e5">جناب آقای <b>اشکان طراوتی</b> <small>به سامانه خوش آمدید.</small> </p>
                3
            </div>
        </div>
    </div>
</div>

<div class="col-lg-6">
    <div class="glob-panel">
        <div class="glob-panel-header">
            <div class="glob-panel-header-icon"><i class="fa fa-envelope fa-2x"></i></div>
            <div class="glob-panel-header-body">
                <h3>پیام‌ها</h3>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="glob-panel-body">
            <table class="glob-pannel-table">
                <thead>
                    <tr>
                        <td>فرستنده</td>
                        <td>موضوع</td>
                        <td></td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>بهزاد</td> 
                        <td>ارجاع پرونده بیمار </td>
                        <td><i class="fa fa-search text-info"></i><i class="fa fa-remove text-danger"></i></td>
                    </tr>
                    <tr>
                        <td>بهزاد</td>
                        <td>ارجاع پرونده بیمار </td>
                        <td><i class="fa fa-search text-info"></i><i class="fa fa-remove text-danger"></i></td>
                    </tr>
                    <tr>
                        <td>بهزاد</td>
                        <td>ارجاع پرونده بیمار </td>
                        <td><i class="fa fa-search text-info"></i><i class="fa fa-remove text-danger"></i></td>

                    </tr>
                </tbody>

            </table>
        </div>
    </div>
</div>
<div class="clearfix"></div>
<div class="row">
    <div class="col-lg-12">
        <div class="glob-panel">
            <div class="glob-panel-header">
                <div class="glob-panel-header-icon" style="width: 5% !important"><i class="fa fa-medkit fa-2x"></i></div>
                <div class="glob-panel-header-body" style="width: calc( 95% - 1px) !important">
                    <h3>‌ویزیتهای امروز</h3>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="glob-panel-body">
            </div>
        </div>
    </div>
</div>

Clinic/Views/Paitient/CreateNewPaitient.cshtml
@{
    Layout = "~/Views/Shared/_DashLayout.cshtml";
    ViewBag.Title = "افزودن بیمارجدید";
}

@section styles
{
    
<link href="~/Content/style_sheet/lib-plugin/persian-datepicker-0.4.5.min.css" rel="stylesheet" />
<link href="~/Content/style_sheet/lib-plugin/persian-datepicker-blue.css" rel="stylesheet" />
}

@section scripts
{
    
<script src="~/Content/script/lib-plugin/persian-date.js"></script>
<script src="~/Content/script/lib-plugin/persian-datepicker-0.4.5.min.js"></script>
<script src="~/Content/script/lib-plugin/jquery.mask.min.js"></script>
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">داشبورد</h1>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="glob-panel">
            <div class="glob-panel-header">
                <div class="glob-panel-header-icon" style="width: 5% !important"><i class="fa fa-user fa-2x"></i></div>
                <div class="glob-panel-header-body" style="width: calc( 95% - 1px) !important">
                    <h3>‌مشخصات فردی</h3>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="glob-panel-body" style="height: 500px">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label>نام بیمار</label>
                        <input class="form-control">
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label>نام خانوادگی </label>
                        <input class="form-control">
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label>تاریخ ثبت  </label>
                        <input class="form-control date">
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label>آدرس  </label>
                        <textarea class="form-control" rows="3"></textarea>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label>تلفن  </label>
                        <input class="form-control phone">
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label>تلفن ثابت  </label>
                        <input class="form-control home-phone">
                    </div>
                </div>
                <div class="clearfix"></div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <div class="row" style="margin-right: 1px;">
                            <label>بیماری‌های خاص</label>
                        </div>
                        <div class="col-lg-3">
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" value="">آسم

                                </label>
                            </div>
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" value="">دیابت

                                </label>
                            </div>
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" value="">فشار خون

                                </label>
                            </div>
                        </div>
                        <div class="col-lg-3">
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" value="">آسم

                                </label>
                            </div>
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" value="">دیابت

                                </label>
                            </div>
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" value="">فشار خون

                                </label>
                            </div>
                        </div>
                        <div class="col-lg-3">
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" value="">آسم

                                </label>
                            </div>
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" value="">دیابت

                                </label>
                            </div>
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" value="">فشار خون

                                </label>
                            </div>
                        </div>

                        <div class="clearfix"></div>
                    </div>
                </div>

            </div>



        </div>
    </div>
</div>
<script type="text/javascript">
        $(document).ready(function () {
            $(".date")
                .pDatepicker({
                    justSelectOnDate: true,
                });
        });
        $('.phone').mask('0000-000-00-00');
        $('.home-phone').mask('0000-0000');
</script>

Clinic/Views/Paitient/ListOfPaitients.cshtml
@{
    ViewBag.Title = "لیست بیماران";
    Layout = "~/Views/Shared/_DashLayout.cshtml";
}
<link href="~/Content/style_sheet/app/app.css" rel="stylesheet" />
<div class="row">
    <div class="col-lg-12">
        <div class="panel-body" style="padding-right:0px !important">
            <div class="panel-group" id="accordion">
                <div class="panel panel-default" style="border:none !important">
                    <div class="panel-heading" style="background:#fff !important;border:none !important;padding-right:0px !important">
                        <h2 class="page-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" class="" style="color:#073d5c !important;text-decoration:none;">
                                جست‌وجو بیمار
                            </a>
                        </h2>
                    </div>
                    <div id="collapseOne" class="panel-collapse collapse">
                        <div class="panel-body">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label>نام بیمار</label>
                                    <input class="form-control">
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label> شماره پرونده  </label>
                                    <input class="form-control date">
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label>نام دکتر</label>
                                    <select class="form-control phone"></select>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label>.....   </label>
                                    <input class="form-control home-phone">
                                </div>
                            </div>
                            <button class="btn btn-block glob-btn-primary">جست و جو </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header" style="margin-top:0px !important;">لیست بیماران</h1>
    </div>
</div>

<div class="row" id="main">
    <div class="col-lg-12">
        <table class="glob-table col-lg-12">
            <thead>
                <tr>
                    <td></td>
                    <td>شماره پرونده</td>
                    <td>نام</td>
                    <td>تاریخ آخرین ویزیت</td>
                    <td>نام دکتر</td>
                    <td>بدهکار</td>
                    <td></td>

                </tr>
            </thead>

            <tbody>
                <tr>
                    <td class="glob-table-fa-info"><i class="fa fa-info-circle" data-toggle="tooltip" data-placement="bottom" title="مشاهده پرونده"></i></td>
                    <td>645456</td>
                    <td>اشکان طراوتی</td>
                    <td>95-9-20 19:24</td>
                    <td>رستگار</td>
                    <td>0</td>
                    <td class="">
                        <a href="" class="glob-table-add-visit" data-toggle="tooltip" data-placement="bottom" title="افزودن ویزیت"> <i class="fa fa-plus"></i></a>
                        <a href="" class="glob-table-delete" data-toggle="tooltip" data-placement="bottom" title="حذف بیمار"> <i class="fa fa-minus"></i></a>
                    </td>
                </tr>
                <tr>
                    <td class="glob-table-fa-info"><i class="fa fa-info-circle" data-toggle="tooltip" data-placement="bottom" title="مشاهده پرونده"></i></td>
                    <td>645456</td>
                    <td>اشکان طراوتی</td>
                    <td>95-9-20 19:24</td>
                    <td>نارستگار</td>
                    <td>0</td>
                    <td class="">
                        <a href="" class="glob-table-add-visit" data-toggle="tooltip" data-placement="bottom" title="افزودن ویزیت"> <i class="fa fa-plus"></i></a>
                        <a href="" class="glob-table-delete" data-toggle="tooltip" data-placement="bottom" title="حذف بیمار"> <i class="fa fa-minus"></i></a>
                    </td>
                </tr>
                <tr>
                    <td class="glob-table-fa-info"><i class="fa fa-info-circle" data-toggle="tooltip" data-placement="bottom" title="مشاهده پرونده"></i></td>
                    <td>645456</td>
                    <td>اشکان طراوتی</td>
                    <td>95-9-20 19:24</td>
                    <td>رستگار</td>
                    <td>0</td>
                    <td class="">
                        <a href="" class="glob-table-add-visit" data-toggle="tooltip" data-placement="bottom" title="افزودن ویزیت"> <i class="fa fa-plus"></i></a>
                        <a href="" class="glob-table-delete" data-toggle="tooltip" data-placement="bottom" title="حذف بیمار"> <i class="fa fa-minus"></i></a>
                    </td>
                </tr>
            </tbody>
        </table>
        <script>
            $(function () {
                $('[data-toggle="tooltip"]').tooltip()
            })

            $("#main").click(function () {
                $("#collapseOne").removeClass("collapse");
                $("#collapseOne").addClass("in");
                $("#collapseOne").addClass("collapse");
            });
        </script>
    </div>
</div>

Clinic/Views/Shared/AdminMetisMenu.cshtml
<div class="sidebar-nav navbar-collapse">
    <ul class="nav" id="side-menu">
        <li class="sidebar-search" style="padding: 45px"></li>
        <li>
            <a href="@Url.Action("Dashboard", "Home")"><i class="fa fa-home fa-fw"></i>خانه</a>
        </li>
        <li>
            <a href="#"><i class="fa fa-stethoscope fa-fw"></i>مدیریت بیماران<span class="fa arrow"></span></a>
            <ul class="nav nav-second-level">
                <li>
                    <a href="@Url.Action("CreateNewPaitient", "Paitient")">افزودن بیمار جدید</a>
                </li>
                <li>
                    <a href="@Url.Action("ListOfPaitient", "Paitient")">لیست بیماران</a>
                </li>
                <li>
                    <a href="#">گزارش سریع</a>
                </li>
            </ul>
            <!-- /.nav-second-level -->
        </li>
        <li>
            <a href="#"><i class="fa fa-pencil fa-fw"></i>مدیریت ویزیت‌ها<span class="fa arrow"></span></a>
            <ul class="nav nav-second-level"></ul>
        </li>
        <li>
            <a href="#"><i class="fa fa-users fa-fw"></i>مدیریت کاربران<span class="fa arrow"></span></a>
        </li>
        <li>
            <a href="#"><i class="fa fa-wrench fa-fw"></i>... <span class="fa arrow"></span></a>
            <ul class="nav nav-second-level"></ul>
            <!-- /.nav-second-level -->
        </li>
    </ul>
</div>

Clinic/Views/Shared/_DashLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <title>@ViewBag.Title - سامانه مدیریت کلینیک</title>
    <link href="../Content/style_sheet/lib-plugin/bootstrap.min.css" rel="stylesheet" />
    <link href="../Content/style_sheet/app/app-sb.css" rel="stylesheet" />
    <link href="../Content/style_sheet/fonts/font-awesome/font-awesome.min.css" rel="stylesheet" />
    <link href="../Content/style_sheet/app/app.css" rel="stylesheet" />
    @RenderSection("styles", required: false)
    <script src="../Content/script/lib-plugin/jquery-1.11.0.js"></script>
    <script src="../Content/script/lib-plugin/bootstrap.min.js"></script>
    <script src="../Content/script/lib-plugin/metisMenu.min.js"></script>
    <script src="../Content/script/app/app-sb.js"></script>
    @RenderSection("scripts", required: false)
</head>
<body>
    @*@{
            var id = Convert.ToInt32(Session["uid"].ToString());
            var u = new Clinic.Models.ClinicEntities1().Users.FirstOrDefault(us => us.Id == id); ;
        }*@
    <div id="wrapper">
        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">سامانه‌‌ی مدیریت کلینیک</a>
            </div>
            <!-- /.navbar-header -->
            <ul class="nav navbar-top-links navbar-left">
                <!-- /.dropdown -->
                <li class="dropdown pull-left">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i><i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li>
                            <a href="#"><i class="fa fa-user fa-fw"></i>نمایه</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-gear fa-fw"></i>تنظیمات</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="@Url.Action("LogOut", "Account")"><i class="fa fa-sign-out fa-fw"></i>خروج</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->
            <div class="navbar-default sidebar" role="navigation">
                @Html.Partial("~/Views/Shared/AdminMetisMenu.cshtml")
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>
        <!-- Page Content -->
        <div id="page-wrapper">
            @RenderBody()
        </div>
        <!-- /#page-wrapper -->
    </div>
</body>
</html>